@CityInfo.API_HostAddress = https://localhost:7139

POST {{CityInfo.API_HostAddress}}/api/Authentication/Authenticate
Content-Type: application/json

{
  //AuthenticationRequestBody
}

###

GET {{CityInfo.API_HostAddress}}/api/v{version:apiVersion}/cities?name=string&searchQuery=string

###
